# Nome da aplicação
spring.application.name=e-comercecafe

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DataBaseEcommerceCafe
spring.datasource.username=postgres
spring.datasource.password=laedfalu
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false

# Configuração do Flyway para migração de banco de dados
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration 

# Configuração de inicialização de banco de dados (executa SQL na inicialização)
spring.sql.init.mode=always

# Configuração do Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html
